import Head from 'next/head'
import Page from '../components/page'
const Home = () => {
  return (
    <Page>
      <Head>
        <title>SwapThings ⚡️</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Page>
  )
}

export default Home
